# Tensor
##### 텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조이다. 파이토치에서는 텐서를 사용하여 모델의 input, output 그리고 모델의 매개변수들을 encode 한다.
##### 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy 의 ndarray 와 비슷하다. 
##### 텐서는 자동미분(automatic differentiation)에 최적화되어 있다.

In [1]:
import torch 
import numpy as np

# 텐서 초기화
###### 1) 데이터로부터 직접 생성하기
###### 2) NumPy 배열로부터 생성하기 (반대로도 가능)
###### 3) 다른 텐서로부터 생성하기
###### 4) 무작위(random) or 상수(constant) 값을 사용하기

In [2]:
#1
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
#2
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
#3
x_ones = torch.ones_like(x_data) # x_data 의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n" )

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1331, 0.9542],
        [0.7027, 0.9507]]) 



###### shape 은 텐서의 차원을 나타내는 tuple이다.



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.rand(shape)
zeros_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}\n")

Random Tensor: 
 tensor([[0.2772, 0.2153, 0.4699],
        [0.5677, 0.8484, 0.5066]])

Ones Tensor: 
 tensor([[0.0954, 0.9332, 0.9592],
        [0.5894, 0.0264, 0.4745]])

Zeros Tensor: 
 tensor([[0.9873, 0.0749, 0.6203],
        [0.5208, 0.0211, 0.7792]])



##### 텐서의 속성은 텐서의 shape, datatype(자료형) 및 어느 장치에 저장되는지를 나타낸다.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}\n")
print(f"Datatype of tensor: {tensor.dtype}\n")
print(f"Device tensor is stored on: {tensor.device}\n")

Shape of tensor: torch.Size([3, 4])

Datatype of tensor: torch.float32

Device tensor is stored on: cpu



# 텐서 연산(Tensor Operation)


*   각 연산들은 GPU에서 실행가능(CPU보다 빠름)
*   기본적으로 텐서는 CPU에 생성되는데 .to 를 사용하면 GPU 의 availability 를 확인하고 GPU 로 텐서를 이동할 수 있음. 
*   장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이듦.



In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]} ")
print(f"First column: {tensor[:,0]} ")
print(f"Last column: {tensor[:,-1]} ")
tensor[:,1] = 0
print(tensor)
print(f"First row: {tensor[0]} ")

First row: tensor([1., 1., 1., 1.]) 
First column: tensor([1., 1., 1., 1.]) 
Last column: tensor([1., 1., 1., 1.]) 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
First row: tensor([1., 0., 1., 1.]) 


# Tensor merge
##### torch.cat() vs torch.stack()
##### torch.cat() 은 (4,4) shape 의 tensor 3개를 concatenation -> result 텐서는 (12,4) shape 을 가짐
##### torch.stack() 은 말그대로 스택을 쌓는것, (4,4) shape 의 tensor 3개를 stack -> result 텐서는 (3,4,4) 의 크기를 갖게됨.

In [9]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
t2 = torch.stack([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


# Arithmetic Operations

In [12]:
y1 = tensor @ tensor.T
print(tensor.T)
print(f"y1: {y1} \n")

y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y2: {y2} \n")
print(f"y3: {y3} \n")


z1 = tensor * tensor 
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)

print(f"z1: {z1} \n")
print(f"z2: {z2} \n")
print(f"z3: {z3} \n")

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [13]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


##### in-place(바꿔치기) operation - 연산 결과를 피연산자(operand)에 저장하는 연산 
ex) x.copy_(y) , x.t_() 

##### in-place operation 은 메모리를 일부 절약하지만, history 가 즉시 삭제되어 derivative calculation 에 문제가 발생할 수 있음, 그래서 사용을 권장하지 않는다.

In [14]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor) # NOTE *** - in-place operation is~~~

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}\n")

t.add_(2)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"n: {n}")
print(f"t: {t} \n")

np.add(n, 5, out = n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

n: [6. 6. 6. 6. 6.]
t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
